# -*- coding: utf-8 -*-
"""Prueba01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RAgQiqVR4PP7uuXKf3QwWpcY_ATa063W

# Título principal

## Primer tema
"""

print("Hola Mundo")

a=5
b=7

print(a+b)

import pandas as pd

datos = pd.DataFrame({"manzanas":[3,2], "peras":[1,4]}, index=["Juan","Pedro"])
datos

datos.plot.bar()